# Derived from https://github.com/travis-ci-tester/toolchain-table

language:
  - cpp

sudo:
  - false

dist:
  - trusty

cache:
  directories:
    - .hunter

addons:
  apt:
    packages:
      - valgrind
      - libc6-dev
      - libc++-dev

matrix:
  include:
    # Linux {
    - os: linux
      env: CONFIG=Debug TOOLCHAIN=clang-libstdcxx
    - os: linux
      env: CONFIG=Debug TOOLCHAIN=gcc

    # OSX {
    - os: osx
      env: CONFIG=Debug TOOLCHAIN=clang-libstdcxx
    - os: osx
      env: CONFIG=Debug TOOLCHAIN=osx-10-12
    - os: osx
      osx_image: xcode7.3
      env: CONFIG=Debug TOOLCHAIN=ios-nocodesign-9.3
    - os: osx
      osx_image: xcode8
      env: CONFIG=Debug TOOLCHAIN=ios-nocodesign-10-0
    - os: osx
      osx_image: xcode8.1
      env: CONFIG=Debug TOOLCHAIN=ios-nocodesign-10-1
    - os: osx
      osx_image: xcode8.2
      env: CONFIG=Debug TOOLCHAIN=ios-nocodesign-10-2

install:
  # Info about OS
  - uname -a

  # Install Python 3
  - if [[ "`uname`" == "Darwin" ]]; then travis_retry brew install python3; fi

  # Install Python package 'requests'
  # 'easy_install3' is not installed by 'brew install python3' on OS X 10.9 Maverick
  - if [[ "`uname`" == "Darwin" ]]; then pip3 install requests; fi
  - if [[ "`uname`" == "Linux" ]]; then travis_retry pip3 install --user requests; fi

  # Install latest Polly toolchains and scripts
  - wget https://github.com/ruslo/polly/archive/master.zip
  - unzip master.zip
  - POLLY_ROOT="`pwd`/polly-master"

  # Alternatively the exact version can be used:
  # - POLLY_VERSION=0.10.0
  # - wget https://github.com/ruslo/polly/archive/v${POLLY_VERSION}.zip
  # - unzip v${POLLY_VERSION}.zip
  # - POLLY_ROOT="`pwd`/polly-${POLLY_VERSION}"

  - export PATH="${POLLY_ROOT}/bin:${PATH}"

  # Install dependencies (CMake, Android NDK)
  - install-ci-dependencies.py

  # Tune locations
  - export PATH="`pwd`/_ci/cmake/bin:${PATH}"

  # Installed if toolchain is Android (otherwise directory doesn't exist)
  - export ANDROID_NDK_r10e="`pwd`/_ci/android-ndk-r10e"
  - export ANDROID_NDK_r11c="`pwd`/_ci/android-ndk-r11c"

  - export HUNTER_ROOT="`pwd`/.hunter"

script:
  - >
    build.py
    --toolchain ${TOOLCHAIN}
    --config ${CONFIG}
    --test

after_success:
  - bash <(curl -s https://codecov.io/bash)
