language:
  - cpp

sudo:
  - false

dist:
  - trusty

addons:
  apt:
    packages:
      - valgrind
      - libc6-dev
      - libc++-dev

matrix:
  include:
    - os: osx
      osx_image: xcode9
      env: PLATFORM=mac COVERAGE=ON
    - os: osx
      osx_image: xcode8.3
      env: PLATFORM=mac COVERAGE=ON
    - os: osx
      osx_image: xcode9
      env: PLATFORM=ios
    - os: osx
      osx_image: xcode8.3
      env: PLATFORM=ios

install:
  - pip install plumbum

before_script:
  - scripts/build_deps.py $PLATFORM

script:
  - scripts/travis.sh

after_success:
  - if [ -n "$COVERAGE" ]; then bash <(curl -s https://codecov.io/bash); fi
